### ISSUE TITLE
uuid v 8.0.0 not working on node

### ISSUE THREAD

**Issue by DanielJSottile** [uuidjs/uuid#431]
## uuid v 8.0.0 not working correctly on Node

we installed with npm install uuid to the latest version, and when running our server got this callback:

```
post-delete-nicke-dan@1.0.0 start D:\ThinkfulDrills\post-delete-nicke-dan node src/server.js

internal/modules/cjs/loader.js:621 throw e; ^

Error: No valid exports main found for 'D:\ThinkfulDrills\post-delete-nicke-dan\node_modules\uuid' at resolveExportsTarget (internal/modules/cjs/loader.js:618:9) at applyExports (internal/modules/cjs/loader.js:499:14) at resolveExports (internal/modules/cjs/loader.js:548:12) at Function.Module._findPath (internal/modules/cjs/loader.js:650:22) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27) at Function.Module._load (internal/modules/cjs/loader.js:854:27) at Module.require (internal/modules/cjs/loader.js:1023:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.<anonymous> (D:\ThinkfulDrills\post-delete-nicke-dan\src\app.js:7:24) at Module._compile (internal/modules/cjs/loader.js:1128:30) { code: 'MODULE_NOT_FOUND' } npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! post-delete-nicke-dan@1.0.0 start: node src/server.js npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the post-delete-nicke-dan@1.0.0 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Nick Evelson\AppData\Roaming\npm-cache\_logs\2020-04-30T19_37_28_990Z-debug.log
```

## To Reproduce

1. Install 'npm install uuid'
2. Run 'npm start' as a script to run the server/app
3. See error

## Expected behavior

I expected it behave normally, but this is a new patch.

## Runtime

- OS: [Windows 10]
- Runtime: [Node.js]
- Runtime Version: [13.3.0]

**Comment by TrySound** [comment]
See this issue https://github.com/uuidjs/uuid/issues/428

**Comment by ctavan** [comment]
Yes. Please upgrade to latest node 13.x or 14. https://github.com/uuidjs/uuid/issues/428#issuecomment-621519202
