### ISSUE TITLE
UUID fails to load on node 13.5.0

### ISSUE THREAD

**Issue by cloudpremise** [uuidjs/uuid#440]
## Describe the bug
I am unable to load UUID using Node v.13.5.0 on Catalina v10.15.2.

## To Reproduce

1. nvm use default (which currently points to v13.5.0)
2. npm install uuid
3. attempt to run local.js file with:
const { v4: uuidv4 } = require('uuid');
delcared in global.
4. Receive error:
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/greg/Dev/repos/searchmysocial-async/dynamoScanOperations/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/greg/Dev/repos/searchmysocial-async/dynamoScanOperations/lambda.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}

5. so revert nvm using: nvm use v12.14.0
6. node local.js.  Program executes successfully.

## Expected behavior
I should be able to use UUID with latest version of node.

## Runtime

- OS: macOS, Catalina
- Runtime: Node.js from zsh
- Runtime Version: v13.5.0

## Additional context
My package.json includes the following:

    "uuid": "^8.0.0"

**Comment by LinusU** [comment]
Node.js verison 13.5.x is not supported by UUID v8.x, upgrade to a later version of Node.js 13.x, or to Node.js 14.x.

see #428
