### ISSUE TITLE
Package subpath './package.json' is not defined by "exports" in node_modules/uuid/package.json

### ISSUE THREAD

**Issue by evdama** [uuidjs/uuid#442]
```
Package subpath './package.json' is not defined by "exports" in node_modules/uuid/package.json
```

I'm getting this error going from uuid v7.0.3 to v8.0.0. That's the only change I made, no other package or app code changed. Node is v14.1.0 which works with uuid v7.0.3.

I also found a SO post about it, no solution so far either https://stackoverflow.com/questions/61621828/getting-strange-error-using-uuid-npm-module-what-am-i-doing-wrong

**Comment by ctavan** [comment]
Please create a [new bug report using the bug report template that we provide](https://github.com/uuidjs/uuid/issues/new?assignees=&labels=&template=bug_report.md&title=). We are happy to help you, but we need a certain amount of information to deal with your request.

**Comment by jonathanrfisher1** [comment]
I had similar issue and reverted to 7.0.3 and it went away.  I had this error message:

`internal/modules/cjs/loader.js:491
2020-06-24T02:01:26.104483+00:00 app[web.1]: throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
2020-06-24T02:01:26.104484+00:00 app[web.1]: ^
2020-06-24T02:01:26.104484+00:00 app[web.1]: 
2020-06-24T02:01:26.104484+00:00 app[web.1]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /app/node_modules/uuid/package.json
2020-06-24T02:01:26.104485+00:00 app[web.1]: at applyExports (internal/modules/cjs/loader.js:491:9)
2020-06-24T02:01:26.104485+00:00 app[web.1]: at resolveExports (internal/modules/cjs/loader.js:507:23)
2020-06-24T02:01:26.104485+00:00 app[web.1]: at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
2020-06-24T02:01:26.104486+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
2020-06-24T02:01:26.104486+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2020-06-24T02:01:26.104486+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-06-24T02:01:26.104486+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-24T02:01:26.104487+00:00 app[web.1]: at Object.<anonymous> (/app/weather.js:7:14)
2020-06-24T02:01:26.104487+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-24T02:01:26.104487+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
2020-06-24T02:01:26.104487+00:00 app[web.1]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2020-06-24T02:01:26.104488+00:00 app[web.1]: }
2020-06-24T02:01:26.112568+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-06-24T02:01:26.112830+00:00 app[web.1]: npm ERR! errno 1
2020-06-24T02:01:26.113826+00:00 app[web.1]: npm ERR! simpleconnectordemo@1.0.0 start: `node connector.js`
2020-06-24T02:01:26.113950+00:00 app[web.1]: npm ERR! Exit status 1
2020-06-24T02:01:26.114077+00:00 app[web.1]: npm ERR!
2020-06-24T02:01:26.114190+00:00 app[web.1]: npm ERR! Failed at the simpleconnectordemo@1.0.0 start script.
2020-06-24T02:01:26.114290+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-06-24T02:01:26.123278+00:00 app[web.1]: 
2020-06-24T02:01:26.123495+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-06-24T02:01:26.123622+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-06-24T02_01_26_115Z-debug.log`

Hope it helps.

**Comment by jonathanrfisher1** [comment]
Here is my usage:

const uuid = require('uuid/v4');
id: uuid()

node --version
v10.16.0

**Comment by TrySound** [comment]
@jonathanrfisher1 See changelog. `uuid/v4` support was removed.
https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29

**Comment by jonathanrfisher1** [comment]
Thank you! =)
