### ISSUE TITLE
TypeError: Stringified UUID is invalid

### ISSUE THREAD

**Issue by emcpow2** [uuidjs/uuid#608]
## Describe the bug

I'm converting [ulid](https://github.com/perry-mitchell/ulidx) to uuid.

The code is being backported from python to javascript raises an error.

## How to reproduce

```typescript
import { stringify as stringifyUuid } from "uuid"
import { ulidToBytes } from "./ulidToUuid"

test("convert ulid to uuid", () => {
    const referenceUlid = '01FQTRH9ACSDWXVX5NR2V620NG'
    const referenceUuid = '017df588-a54c-cb79-ddf4-b5c0b66102b0'
    const referenceBytes = new Uint8Array([1, 125, 245, 136, 165, 76, 203, 121, 221, 244, 181, 192, 182, 97, 2, 176])

    expect(ulidToBytes(referenceUlid)).toEqual(referenceBytes)
    expect(stringifyUuid(ulidToBytes(referenceUlid))).toEqual(referenceUuid)
})
```

```console
  ● convert ulid to uuid

    TypeError: Stringified UUID is invalid

      30 |
      31 |     expect(ulidToBytes(referenceUlid)).toEqual(referenceBytes)
    > 32 |     expect(stringifyUuid(ulidToBytes(referenceUlid))).toEqual(referenceUuid)
         |                         ^
      33 | })
      34 |

      at stringify (node_modules/uuid/dist/stringify.js:32:11)
      at Object.<anonymous> (src/ulidToUuid.test.ts:32:25)
```

### `ulidToUuid.ts`

```typescript
export function ulidToBytes(ulid: string): Uint8Array {
    const encoder = new TextEncoder()
    const encoded = encoder.encode(ulid)

    const decoding = new Uint8Array([
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x01,
        0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E,
        0x0F, 0x10, 0x11, 0x01, 0x12, 0x13, 0x01, 0x14, 0x15, 0x00,
        0x16, 0x17, 0x18, 0x19, 0x1A, 0xFF, 0x1B, 0x1C, 0x1D, 0x1E,
        0x1F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x0A, 0x0B, 0x0C,
        0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x01, 0x12, 0x13, 0x01, 0x14,
        0x15, 0x00, 0x16, 0x17, 0x18, 0x19, 0x1A, 0xFF, 0x1B, 0x1C,
        0x1D, 0x1E, 0x1F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    ])

    const bytes = [
        ((decoding[encoded[0]] << 5) | decoding[encoded[1]]) & 0xFF,
        ((decoding[encoded[2]] << 3) | (decoding[encoded[3]] >> 2)) & 0xFF,
        ((decoding[encoded[3]] << 6) | (decoding[encoded[4]] << 1) | (decoding[encoded[5]] >> 4)) & 0xFF,
        ((decoding[encoded[5]] << 4) | (decoding[encoded[6]] >> 1)) & 0xFF,
        ((decoding[encoded[6]] << 7) | (decoding[encoded[7]] << 2) | (decoding[encoded[8]] >> 3)) & 0xFF,
        ((decoding[encoded[8]] << 5) | (decoding[encoded[9]])) & 0xFF,
        ((decoding[encoded[10]] << 3) | (decoding[encoded[11]] >> 2)) & 0xFF,
        ((decoding[encoded[11]] << 6) | (decoding[encoded[12]] << 1) | (decoding[encoded[13]] >> 4)) & 0xFF,
        ((decoding[encoded[13]] << 4) | (decoding[encoded[14]] >> 1)) & 0xFF,
        ((decoding[encoded[14]] << 7) | (decoding[encoded[15]] << 2) | (decoding[encoded[16]] >> 3)) & 0xFF,
        ((decoding[encoded[16]] << 5) | (decoding[encoded[17]])) & 0xFF,
        ((decoding[encoded[18]] << 3) | (decoding[encoded[19]] >> 2)) & 0xFF,
        ((decoding[encoded[19]] << 6) | (decoding[encoded[20]] << 1) | (decoding[encoded[21]] >> 4)) & 0xFF,
        ((decoding[encoded[21]] << 4) | (decoding[encoded[22]] >> 1)) & 0xFF,
        ((decoding[encoded[22]] << 7) | (decoding[encoded[23]] << 2) | (decoding[encoded[24]] >> 3)) & 0xFF,
        ((decoding[encoded[24]] << 5) | (decoding[encoded[25]])) & 0xFF
    ]

    return new Uint8Array(bytes)
}
```

## Expected behavior

uuid library generates uuid string from ulid bytes representation.

## Runtime

- OS: macOS, Linux
- Runtime: Node.js
- Runtime Version: v14.18.1

## Additional information

I was able to successfully test on this example. Also python works for both cases([source](https://github.com/ahawker/ulid/blob/v1.1.0/ulid/ulid.py#L334-L342))

```typescript
test("experiment with ulid decoding", () => {
    const referenceUlid = '000XAL6S41ACTAV9WEVGEMMVR8'
    const referenceUuid = '00075413-6481-5334-ada7-8edc1d4a6f08'
    const referenceHex = '0007541364815334ada78edc1d4a6f08'
    const referenceBytesString = '\x00\x07T\x13d\x81S4\xad\xa7\x8e\xdc\x1dJo\x08'
    const referenceBytes = new Uint8Array([0, 7, 84, 19, 100, 129, 83, 52, 173, 167, 142, 220, 29, 74, 111, 8])
    expect(stringifyUuid(Buffer.from(referenceHex, 'hex'))).toEqual(referenceUuid)


    expect(ulidToBytes(referenceUlid)).toEqual(referenceBytes)
    expect(stringifyUuid(ulidToBytes(referenceUlid))).toEqual(referenceUuid)
})
```

### Validate

```
import { validate as validateUuid } from "uuid"

validateUuid('00075413-6481-5334-ada7-8edc1d4a6f08') == true

validateUuid('017df588-a54c-cb79-ddf4-b5c0b66102b0') == false
```

**Comment by broofa** [comment]
This isn't an issue with this library.  Translating ULIDs to UUIDs isn't quite that easy, for a couple reasons:

1. RFC4122 requires [variant](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.1) and [version](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.3) fields be set properly.  This is the issue you're running into - one or both of those fields is not set properly in the bytes you're passing to `stringify()`.
2. Related to the above, while ULIDs and UUIDs both contain the same number of bits (128), UUIDs reserve 6 of those for the above fields.   So you'll have to discard 6 bits of ULID data somewhere (probably from the random portion of the ULID).  The net result is that a symmetric conversion isn't possible.  Just something to be aware of.
3. Because ULIDs encode a timestamp, a "strict" conversion should technically result in a version 1 (timestamp) UUID.   However ULIDs use the unix epoch (milliseconds), while UUIDs use the gregorian epoch (100-nanoseconds).  Converting between these two is [non-trivial](https://github.com/uuidjs/uuid/blob/main/src/v1.js#L49-L99).

If you _really_ want to convert ULID to UUID, you may find it simpler to use the `v1()` method, and pass an appropriate `options` argument.  Specifically:
* Pass the ulid timestamp as `msecs` (47 bits)
* Divide up the remaining random ULID bits among the `nsecs` (13 bits) , `clockseq` (14 bits), and `node` (48 bits) fields
