### ISSUE TITLE
[BUG] <

### ISSUE THREAD

**Issue by agracia-foticos** [uuidjs/uuid#694]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

[nuxt] [request error] [unhandled] [500] Package subpath './v4' is not defined by "exports" in /var/www/wanapix_next/.output/server/node_modules/uuid/package.json
  at new NodeError (node:internal/errors:393:5)
  at exportsNotFound (node:internal/modules/esm/resolve:292:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:628:9)
  at resolveExports (node:internal/modules/cjs/loader:531:36)
  at Module._findPath (node:internal/modules/cjs/loader:600:31)
  at Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
  at Module._load (node:internal/modules/cjs/loader:872:27)
  at Module.require (node:internal/modules/cjs/loader:1092:19)
  at require (node:internal/modules/cjs/helpers:103:18)
  at Object.<anonymous> (./.output/server/node_modules/analytics-node/index.js:9:14)

### Recipe for reproducing

```bash
[nuxt] [request error] [unhandled] [500] Package subpath './v4' is not defined by "exports" in /var/www/wanapix_next/.output/server/node_modules/uuid/package.json
  at new NodeError (node:internal/errors:393:5)
  at exportsNotFound (node:internal/modules/esm/resolve:292:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:628:9)
  at resolveExports (node:internal/modules/cjs/loader:531:36)
  at Module._findPath (node:internal/modules/cjs/loader:600:31)
  at Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
  at Module._load (node:internal/modules/cjs/loader:872:27)
  at Module.require (node:internal/modules/cjs/loader:1092:19)
  at require (node:internal/modules/cjs/helpers:103:18)
  at Object.<anonymous> (./.output/server/node_modules/analytics-node/index.js:9:14)
```

### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.4.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `@nuxtjs/i18n-edge@8.0.0-beta.9-27948515.3db6367`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

**Comment by broofa** [comment]
@agracia-foticos:  This is not an issue with `uuid`, it's an issue inside your dependency tree.

Try removing your `node_modules` directory and reinstalling.
